blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: mailto:security@orb.zone
    about: Please report security issues privately via email
  - name: Question or Discussion
    url: https://github.com/orb-zone/dotted-json/discussions
    about: Ask questions or discuss ideas with the community
