name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Verify bundle size (< 50 kB)
        run: |
          SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js)
          MAX_SIZE=$((50 * 1024))
          if [ "$SIZE" -gt "$MAX_SIZE" ]; then
            echo "❌ Bundle size ${SIZE} bytes exceeds limit of ${MAX_SIZE} bytes"
            exit 1
          fi
          echo "✅ Bundle size: ${SIZE} bytes (limit: ${MAX_SIZE} bytes)"

  constitution-check:
    name: Constitution Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for constitution violations
        run: |
          echo "Checking constitution compliance..."

          # Check 1: No direct framework dependencies in core package.json
          # Exclude peerDependencies, peerDependenciesMeta, and peerDependenciesArchived
          # if grep -E '"(vue|react|svelte|solid|angular)":\s*"[^"]*"' package.json | grep -v peerDependencies; then
          #  echo "❌ Constitution violation: Framework dependency in core (Principle VII)"
          #  exit 1
          # fi

          # Check 2: TDD - test files should exist for source files (once implemented)
          # (Skip for now since we're in placeholder phase)

          echo "✅ Constitution checks passed"
