name: Publish to JSR

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  id-token: write  # Required for JSR OIDC authentication

jobs:
  publish:
    # Only run if the PR was merged and title contains "version packages"
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'version packages')
    name: Publish to JSR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Package
        run: bun run build

      - name: Publish to JSR
        run: bunx jsr publish --allow-dirty
